openapi: 3.0.1
info:
  title: Echo Service
  description: |-
    Echo Service API consists of a single service which returns
    a message.
  version: version not set
servers:
- url: /
tags:
- name: EchoService
paths:
  /v1/example/echo/{id}:
    post:
      tags:
      - EchoService
      summary: Echo method receives a simple message and returns it.
      description: |-
        The message posted as the id parameter will also be
        returned.
      operationId: EchoServiceEchoService_Echo
      parameters:
      - name: id
        in: path
        description: Id represents the message identifier.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/examplepbSimpleMessage'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
  /v1/example/echo/{id}/{num}:
    get:
      tags:
      - EchoService
      summary: Echo method receives a simple message and returns it.
      description: |-
        The message posted as the id parameter will also be
        returned.
      operationId: EchoServiceEchoService_Echo2
      parameters:
      - name: id
        in: path
        description: Id represents the message identifier.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: num
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: int64
      - name: lineNum
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: int64
      - name: lang
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: status.progress
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: int64
      - name: status.note
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: en
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: int64
      - name: no.progress
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: int64
      - name: no.note
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/examplepbSimpleMessage'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
  /v1/example/echo/{id}/{num}/{lang}:
    get:
      tags:
      - EchoService
      summary: Echo method receives a simple message and returns it.
      description: |-
        The message posted as the id parameter will also be
        returned.
      operationId: EchoServiceEchoService_Echo3
      parameters:
      - name: id
        in: path
        description: Id represents the message identifier.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: num
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: int64
      - name: lang
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: lineNum
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: int64
      - name: status.progress
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: int64
      - name: status.note
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: en
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: int64
      - name: no.progress
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: int64
      - name: no.note
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/examplepbSimpleMessage'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
  /v1/example/echo1/{id}/{lineNum}/{status.note}:
    get:
      tags:
      - EchoService
      summary: Echo method receives a simple message and returns it.
      description: |-
        The message posted as the id parameter will also be
        returned.
      operationId: EchoServiceEchoService_Echo4
      parameters:
      - name: id
        in: path
        description: Id represents the message identifier.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: lineNum
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: int64
      - name: status.note
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: num
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: int64
      - name: lang
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: status.progress
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: int64
      - name: en
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: int64
      - name: no.progress
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: int64
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/examplepbSimpleMessage'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
  /v1/example/echo2/{no.note}:
    get:
      tags:
      - EchoService
      summary: Echo method receives a simple message and returns it.
      description: |-
        The message posted as the id parameter will also be
        returned.
      operationId: EchoServiceEchoService_Echo5
      parameters:
      - name: no.note
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: id
        in: query
        description: Id represents the message identifier.
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: num
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: int64
      - name: lineNum
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: int64
      - name: lang
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: status.progress
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: int64
      - name: en
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: int64
      - name: no.progress
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: int64
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/examplepbSimpleMessage'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
  /v1/example/echo_body:
    post:
      tags:
      - EchoService
      summary: EchoBody method receives a simple message and returns it.
      operationId: EchoServiceEchoService_EchoBody
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/examplepbSimpleMessage'
        required: true
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/examplepbSimpleMessage'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      x-codegen-request-body-name: body
  /v1/example/echo_delete:
    delete:
      tags:
      - EchoService
      summary: EchoDelete method receives a simple message and returns it.
      operationId: EchoServiceEchoService_EchoDelete
      parameters:
      - name: id
        in: query
        description: Id represents the message identifier.
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: num
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: int64
      - name: lineNum
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: int64
      - name: lang
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: status.progress
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: int64
      - name: status.note
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: en
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: int64
      - name: no.progress
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: int64
      - name: no.note
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/examplepbSimpleMessage'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
  /v1/example/echo_patch:
    patch:
      tags:
      - EchoService
      summary: EchoPatch method receives a NonStandardUpdateRequest and returns it.
      operationId: EchoServiceEchoService_EchoPatch
      parameters:
      - name: updateMask
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/examplepbDynamicMessage'
        required: true
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/examplepbDynamicMessageUpdate'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      x-codegen-request-body-name: body
components:
  schemas: {}
x-original-swagger-version: "2.0"
