openapi: 3.0.1
info:
  title: examples/internal/proto/examplepb/response_body_service.proto
  version: version not set
servers:
- url: /
tags:
- name: ResponseBodyService
paths:
  /responsebodies/{data}:
    get:
      tags:
      - ResponseBodyService
      operationId: ResponseBodyServiceResponseBodyService_ListResponseBodies
      parameters:
      - name: data
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/examplepbRepeatedResponseBodyOutResponse'
                x-content-type: application/json
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
  /responsebody/stream/{data}:
    get:
      tags:
      - ResponseBodyService
      operationId: ResponseBodyServiceResponseBodyService_GetResponseBodyStream
      parameters:
      - name: data
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: (streaming responses)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stream result of examplepbResponseBodyOut'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
  /responsebody/{data}:
    get:
      tags:
      - ResponseBodyService
      operationId: ResponseBodyServiceResponseBodyService_GetResponseBody
      parameters:
      - name: data
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/examplepbResponseBodyOutResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
  /responsestrings/{data}:
    get:
      tags:
      - ResponseBodyService
      operationId: ResponseBodyServiceResponseBodyService_ListResponseStrings
      parameters:
      - name: data
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                x-content-type: application/json
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
components:
  schemas:
    Stream result of examplepbResponseBodyOut:
      title: Stream result of examplepbResponseBodyOut
      type: object
      properties:
        result:
          $ref: '#/components/schemas/examplepbResponseBodyOutResponse'
        error:
          $ref: '#/components/schemas/rpcStatus'
      example:
        result: "{}"
        error: "{}"
x-original-swagger-version: "2.0"
